### ISSUE TITLE
lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by maangyin** [ahasverus/franceinter#1]
Hi, I got this, could anyone help?
```
> library("radiofrance")
> podcast_name <- "au-temps-pour-moi"
> tab <- get_metadata(podcast_name, radio = "franceinter")
Error: lexical error: invalid char in json text.
                            				{ 					__sveltekit_6qv2xl = { 						en
                     (right here) ------^
```

**Comment by ahasverus** [comment]
Thanks for your message. The problem is fixed now. 
Please reinstall this package w/: `remotes::install_github("ahasverus/radiofrance")` to have the new version.

Note that this package scraps websites, and it may fail again if the source code of the websites changes. I keep an eye on this to update the package consequently.
Nicolas.
